name: hydrometenv
channels:
  - conda-forge
dependencies:
  - bokeh
  - cfgrib
  - dask
  - eccodes==2.18.0-hc7b4307_1
  - fiona
  - geopandas
  - matplotlib
  - netcdf4
  - pandas
  - pynio
  - pyproj
  - rtree
  - scipy
  - shapely
  - xarray
